pipeline {
  agent any
  tools {
    nodejs 'node-16.2.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        bat 'cd jenkins-tests && npm install'
      }
    }
    stage('Run tests') {
      steps {
        bat 'cd jenkins-tests && npm test'
      }
    }
  }
}
